export type Continent =
  | 'Africa'
  | 'Asia'
  | 'Europe'
  | 'North America'
  | 'Oceania'
  | 'South America'

export type FlagLayout =
  | 'horizontal-stripes'
  | 'vertical-stripes'
  | 'diagonal'
  | 'cross'
  | 'canton'
  | 'central-emblem'
  | 'other'

export type FlagTag =
  | 'emblem'
  | 'crescent'
  | 'star'
  | 'sun'
  | 'animal'
  | 'plant'
  | 'weapon'
  | 'text'
  | 'map-silhouette'

export interface Country {
  id: string // globally unique across flag categories, e.g. 'country:us'
  category: 'country' | 'historical'
  code: string // ISO 3166-1 alpha-2, lowercase, matches flag-icons class fi-<code>
  // ('country' entries only — 'historical' entries render via imageUrl instead)
  name: string
  continent: Continent
  colorCount: number
  layout: FlagLayout
  areaKm2: number
  flagRatioW: number // real official flag aspect ratio, e.g. 19/10 for the US
  flagRatioH: number
  nonRectangularFlag?: true // true shape isn't a rectangle at all (e.g. Nepal) — flagRatioW/H is a fallback box, not the real shape
  tags?: FlagTag[] // what's depicted on the flag, e.g. ['emblem', 'animal'] for Mexico
  aliases?: string[] // accepted alternate names for typed-answer matching
  imageUrl?: string // 'historical' entries only — path under public/ to a locally hosted flag SVG (flag-icons has no historical-flag artwork)
  sensitive?: true // 'historical' entries only — politically-charged flags gated behind a separate opt-in
}

// Generated by scripts/generate-flag-metadata.mjs — do not hand-edit the
// id/category/continent/colorCount/layout/areaKm2/flagRatioW/flagRatioH/nonRectangularFlag/tags/aliases
// fields, re-run the script instead. (imageUrl/sensitive are never touched by that
// script — they're exclusive to src/data/historicalFlags.ts.)
export const countries: Country[] = [
  { id: 'country:af', category: 'country', code: 'af', name: "Afghanistan", continent: 'Asia', colorCount: 5, layout: 'vertical-stripes', areaKm2: 652230, flagRatioW: 2, flagRatioH: 1, tags: ["emblem"] },
  { id: 'country:al', category: 'country', code: 'al', name: "Albania", continent: 'Europe', colorCount: 2, layout: 'other', areaKm2: 28748, flagRatioW: 7, flagRatioH: 5, tags: ["animal"] },
  { id: 'country:dz', category: 'country', code: 'dz', name: "Algeria", continent: 'Africa', colorCount: 3, layout: 'other', areaKm2: 2381741, flagRatioW: 3, flagRatioH: 2, tags: ["crescent","star"] },
  { id: 'country:ad', category: 'country', code: 'ad', name: "Andorra", continent: 'Europe', colorCount: 6, layout: 'vertical-stripes', areaKm2: 468, flagRatioW: 10, flagRatioH: 7 },
  { id: 'country:ao', category: 'country', code: 'ao', name: "Angola", continent: 'Africa', colorCount: 5, layout: 'horizontal-stripes', areaKm2: 1246700, flagRatioW: 3, flagRatioH: 2, tags: ["emblem","star","weapon"] },
  { id: 'country:ag', category: 'country', code: 'ag', name: "Antigua and Barbuda", continent: 'North America', colorCount: 5, layout: 'horizontal-stripes', areaKm2: 442, flagRatioW: 3, flagRatioH: 2, tags: ["sun"], aliases: ["Antigua"] },
  { id: 'country:ar', category: 'country', code: 'ar', name: "Argentina", continent: 'South America', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 2780400, flagRatioW: 8, flagRatioH: 5 },
  { id: 'country:am', category: 'country', code: 'am', name: "Armenia", continent: 'Asia', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 29743, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:au', category: 'country', code: 'au', name: "Australia", continent: 'Oceania', colorCount: 3, layout: 'canton', areaKm2: 7692024, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:at', category: 'country', code: 'at', name: "Austria", continent: 'Europe', colorCount: 2, layout: 'horizontal-stripes', areaKm2: 83871, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:az', category: 'country', code: 'az', name: "Azerbaijan", continent: 'Asia', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 86600, flagRatioW: 2, flagRatioH: 1, tags: ["crescent","star"] },
  { id: 'country:bs', category: 'country', code: 'bs', name: "Bahamas", continent: 'North America', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 13943, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:bh', category: 'country', code: 'bh', name: "Bahrain", continent: 'Asia', colorCount: 2, layout: 'other', areaKm2: 765, flagRatioW: 5, flagRatioH: 3 },
  { id: 'country:bd', category: 'country', code: 'bd', name: "Bangladesh", continent: 'Asia', colorCount: 2, layout: 'central-emblem', areaKm2: 147570, flagRatioW: 5, flagRatioH: 3 },
  { id: 'country:bb', category: 'country', code: 'bb', name: "Barbados", continent: 'North America', colorCount: 3, layout: 'vertical-stripes', areaKm2: 430, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:by', category: 'country', code: 'by', name: "Belarus", continent: 'Europe', colorCount: 3, layout: 'vertical-stripes', areaKm2: 207600, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:be', category: 'country', code: 'be', name: "Belgium", continent: 'Europe', colorCount: 3, layout: 'vertical-stripes', areaKm2: 30528, flagRatioW: 15, flagRatioH: 13 },
  { id: 'country:bz', category: 'country', code: 'bz', name: "Belize", continent: 'North America', colorCount: 18, layout: 'other', areaKm2: 22966, flagRatioW: 5, flagRatioH: 3, tags: ["emblem"] },
  { id: 'country:bj', category: 'country', code: 'bj', name: "Benin", continent: 'Africa', colorCount: 3, layout: 'other', areaKm2: 112622, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:bt', category: 'country', code: 'bt', name: "Bhutan", continent: 'Asia', colorCount: 3, layout: 'other', areaKm2: 38394, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:bo', category: 'country', code: 'bo', name: "Bolivia", continent: 'South America', colorCount: 16, layout: 'horizontal-stripes', areaKm2: 1098581, flagRatioW: 22, flagRatioH: 15 },
  { id: 'country:ba', category: 'country', code: 'ba', name: "Bosnia and Herzegovina", continent: 'Europe', colorCount: 3, layout: 'other', areaKm2: 51209, flagRatioW: 2, flagRatioH: 1, tags: ["star"], aliases: ["Bosnia"] },
  { id: 'country:bw', category: 'country', code: 'bw', name: "Botswana", continent: 'Africa', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 582000, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:br', category: 'country', code: 'br', name: "Brazil", continent: 'South America', colorCount: 4, layout: 'central-emblem', areaKm2: 8515767, flagRatioW: 10, flagRatioH: 7, tags: ["star","text"] },
  { id: 'country:bn', category: 'country', code: 'bn', name: "Brunei", continent: 'Asia', colorCount: 4, layout: 'central-emblem', areaKm2: 5765, flagRatioW: 2, flagRatioH: 1, tags: ["emblem"], aliases: ["Brunei Darussalam"] },
  { id: 'country:bg', category: 'country', code: 'bg', name: "Bulgaria", continent: 'Europe', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 110879, flagRatioW: 5, flagRatioH: 3 },
  { id: 'country:bf', category: 'country', code: 'bf', name: "Burkina Faso", continent: 'Africa', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 272967, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:bi', category: 'country', code: 'bi', name: "Burundi", continent: 'Africa', colorCount: 3, layout: 'diagonal', areaKm2: 27834, flagRatioW: 5, flagRatioH: 3, tags: ["star"] },
  { id: 'country:cv', category: 'country', code: 'cv', name: "Cabo Verde", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 4033, flagRatioW: 3, flagRatioH: 2, tags: ["star"], aliases: ["Cape Verde"] },
  { id: 'country:kh', category: 'country', code: 'kh', name: "Cambodia", continent: 'Asia', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 181035, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:cm', category: 'country', code: 'cm', name: "Cameroon", continent: 'Africa', colorCount: 3, layout: 'vertical-stripes', areaKm2: 475442, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:ca', category: 'country', code: 'ca', name: "Canada", continent: 'North America', colorCount: 2, layout: 'vertical-stripes', areaKm2: 9984670, flagRatioW: 2, flagRatioH: 1, tags: ["plant"] },
  { id: 'country:cf', category: 'country', code: 'cf', name: "Central African Republic", continent: 'Africa', colorCount: 5, layout: 'horizontal-stripes', areaKm2: 622984, flagRatioW: 5, flagRatioH: 3, tags: ["star"] },
  { id: 'country:td', category: 'country', code: 'td', name: "Chad", continent: 'Africa', colorCount: 3, layout: 'vertical-stripes', areaKm2: 1284000, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:cl', category: 'country', code: 'cl', name: "Chile", continent: 'South America', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 756102, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:cn', category: 'country', code: 'cn', name: "China", continent: 'Asia', colorCount: 2, layout: 'other', areaKm2: 9706961, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:co', category: 'country', code: 'co', name: "Colombia", continent: 'South America', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 1141748, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:km', category: 'country', code: 'km', name: "Comoros", continent: 'Africa', colorCount: 5, layout: 'horizontal-stripes', areaKm2: 1862, flagRatioW: 5, flagRatioH: 3, tags: ["crescent","star"] },
  { id: 'country:cg', category: 'country', code: 'cg', name: "Congo", continent: 'Africa', colorCount: 3, layout: 'other', areaKm2: 342000, flagRatioW: 3, flagRatioH: 2, aliases: ["Republic of the Congo","Congo-Brazzaville"] },
  { id: 'country:cd', category: 'country', code: 'cd', name: "DR Congo", continent: 'Africa', colorCount: 3, layout: 'diagonal', areaKm2: 2344858, flagRatioW: 4, flagRatioH: 3, tags: ["star"], aliases: ["Democratic Republic of the Congo","DRC","Congo-Kinshasa"] },
  { id: 'country:cr', category: 'country', code: 'cr', name: "Costa Rica", continent: 'North America', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 51100, flagRatioW: 5, flagRatioH: 3 },
  { id: 'country:ci', category: 'country', code: 'ci', name: "Cote d'Ivoire", continent: 'Africa', colorCount: 3, layout: 'vertical-stripes', areaKm2: 322463, flagRatioW: 3, flagRatioH: 2, aliases: ["Ivory Coast"] },
  { id: 'country:hr', category: 'country', code: 'hr', name: "Croatia", continent: 'Europe', colorCount: 4, layout: 'vertical-stripes', areaKm2: 56594, flagRatioW: 2, flagRatioH: 1, tags: ["emblem"] },
  { id: 'country:cu', category: 'country', code: 'cu', name: "Cuba", continent: 'North America', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 109884, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:cy', category: 'country', code: 'cy', name: "Cyprus", continent: 'Europe', colorCount: 3, layout: 'other', areaKm2: 9251, flagRatioW: 3, flagRatioH: 2, tags: ["plant","map-silhouette"] },
  { id: 'country:cz', category: 'country', code: 'cz', name: "Czechia", continent: 'Europe', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 78865, flagRatioW: 3, flagRatioH: 2, aliases: ["Czech Republic"] },
  { id: 'country:dk', category: 'country', code: 'dk', name: "Denmark", continent: 'Europe', colorCount: 2, layout: 'cross', areaKm2: 43094, flagRatioW: 37, flagRatioH: 28 },
  { id: 'country:dj', category: 'country', code: 'dj', name: "Djibouti", continent: 'Africa', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 23200, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:dm', category: 'country', code: 'dm', name: "Dominica", continent: 'North America', colorCount: 8, layout: 'horizontal-stripes', areaKm2: 751, flagRatioW: 2, flagRatioH: 1, tags: ["star","animal"] },
  { id: 'country:do', category: 'country', code: 'do', name: "Dominican Republic", continent: 'North America', colorCount: 7, layout: 'cross', areaKm2: 48671, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:ec', category: 'country', code: 'ec', name: "Ecuador", continent: 'South America', colorCount: 17, layout: 'vertical-stripes', areaKm2: 276841, flagRatioW: 3, flagRatioH: 2, tags: ["emblem"] },
  { id: 'country:eg', category: 'country', code: 'eg', name: "Egypt", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 1002450, flagRatioW: 3, flagRatioH: 2, tags: ["emblem","animal","text"] },
  { id: 'country:sv', category: 'country', code: 'sv', name: "El Salvador", continent: 'North America', colorCount: 18, layout: 'horizontal-stripes', areaKm2: 21041, flagRatioW: 5, flagRatioH: 3, tags: ["text"] },
  { id: 'country:gq', category: 'country', code: 'gq', name: "Equatorial Guinea", continent: 'Africa', colorCount: 5, layout: 'horizontal-stripes', areaKm2: 28051, flagRatioW: 3, flagRatioH: 2, tags: ["emblem","star","plant","text"] },
  { id: 'country:er', category: 'country', code: 'er', name: "Eritrea", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 117600, flagRatioW: 2, flagRatioH: 1, tags: ["plant"] },
  { id: 'country:ee', category: 'country', code: 'ee', name: "Estonia", continent: 'Europe', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 45227, flagRatioW: 11, flagRatioH: 7 },
  { id: 'country:sz', category: 'country', code: 'sz', name: "Eswatini", continent: 'Africa', colorCount: 7, layout: 'horizontal-stripes', areaKm2: 17364, flagRatioW: 3, flagRatioH: 2, tags: ["weapon"], aliases: ["Swaziland"] },
  { id: 'country:et', category: 'country', code: 'et', name: "Ethiopia", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 1104300, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:fj', category: 'country', code: 'fj', name: "Fiji", continent: 'Oceania', colorCount: 8, layout: 'canton', areaKm2: 18272, flagRatioW: 2, flagRatioH: 1, tags: ["emblem"] },
  { id: 'country:fi', category: 'country', code: 'fi', name: "Finland", continent: 'Europe', colorCount: 2, layout: 'cross', areaKm2: 338424, flagRatioW: 18, flagRatioH: 11 },
  { id: 'country:fr', category: 'country', code: 'fr', name: "France", continent: 'Europe', colorCount: 3, layout: 'vertical-stripes', areaKm2: 551695, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:ga', category: 'country', code: 'ga', name: "Gabon", continent: 'Africa', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 267668, flagRatioW: 4, flagRatioH: 3 },
  { id: 'country:gm', category: 'country', code: 'gm', name: "Gambia", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 10689, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:ge', category: 'country', code: 'ge', name: "Georgia", continent: 'Asia', colorCount: 2, layout: 'cross', areaKm2: 69700, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:de', category: 'country', code: 'de', name: "Germany", continent: 'Europe', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 357114, flagRatioW: 5, flagRatioH: 3 },
  { id: 'country:gh', category: 'country', code: 'gh', name: "Ghana", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 238533, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:gr', category: 'country', code: 'gr', name: "Greece", continent: 'Europe', colorCount: 2, layout: 'other', areaKm2: 131990, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:gd', category: 'country', code: 'gd', name: "Grenada", continent: 'North America', colorCount: 3, layout: 'other', areaKm2: 344, flagRatioW: 5, flagRatioH: 3, tags: ["star"] },
  { id: 'country:gt', category: 'country', code: 'gt', name: "Guatemala", continent: 'North America', colorCount: 12, layout: 'vertical-stripes', areaKm2: 108889, flagRatioW: 8, flagRatioH: 5 },
  { id: 'country:gn', category: 'country', code: 'gn', name: "Guinea", continent: 'Africa', colorCount: 3, layout: 'vertical-stripes', areaKm2: 245857, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:gw', category: 'country', code: 'gw', name: "Guinea-Bissau", continent: 'Africa', colorCount: 3, layout: 'other', areaKm2: 36125, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:gy', category: 'country', code: 'gy', name: "Guyana", continent: 'South America', colorCount: 5, layout: 'other', areaKm2: 214969, flagRatioW: 5, flagRatioH: 3 },
  { id: 'country:ht', category: 'country', code: 'ht', name: "Haiti", continent: 'North America', colorCount: 5, layout: 'horizontal-stripes', areaKm2: 27750, flagRatioW: 5, flagRatioH: 3 },
  { id: 'country:hn', category: 'country', code: 'hn', name: "Honduras", continent: 'North America', colorCount: 2, layout: 'horizontal-stripes', areaKm2: 112492, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:hu', category: 'country', code: 'hu', name: "Hungary", continent: 'Europe', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 93028, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:is', category: 'country', code: 'is', name: "Iceland", continent: 'Europe', colorCount: 3, layout: 'cross', areaKm2: 103000, flagRatioW: 25, flagRatioH: 18 },
  { id: 'country:in', category: 'country', code: 'in', name: "India", continent: 'Asia', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 3287590, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:id', category: 'country', code: 'id', name: "Indonesia", continent: 'Asia', colorCount: 2, layout: 'horizontal-stripes', areaKm2: 1904569, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:ir', category: 'country', code: 'ir', name: "Iran", continent: 'Asia', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 1648195, flagRatioW: 7, flagRatioH: 4, tags: ["emblem","text"], aliases: ["Islamic Republic of Iran"] },
  { id: 'country:iq', category: 'country', code: 'iq', name: "Iraq", continent: 'Asia', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 438317, flagRatioW: 3, flagRatioH: 2, tags: ["text"] },
  { id: 'country:ie', category: 'country', code: 'ie', name: "Ireland", continent: 'Europe', colorCount: 3, layout: 'vertical-stripes', areaKm2: 70273, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:il', category: 'country', code: 'il', name: "Israel", continent: 'Asia', colorCount: 2, layout: 'horizontal-stripes', areaKm2: 20770, flagRatioW: 11, flagRatioH: 8, tags: ["star"] },
  { id: 'country:it', category: 'country', code: 'it', name: "Italy", continent: 'Europe', colorCount: 3, layout: 'vertical-stripes', areaKm2: 301336, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:jm', category: 'country', code: 'jm', name: "Jamaica", continent: 'North America', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 10991, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:jp', category: 'country', code: 'jp', name: "Japan", continent: 'Asia', colorCount: 2, layout: 'central-emblem', areaKm2: 377930, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:jo', category: 'country', code: 'jo', name: "Jordan", continent: 'Asia', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 89342, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:kz', category: 'country', code: 'kz', name: "Kazakhstan", continent: 'Asia', colorCount: 2, layout: 'other', areaKm2: 2724900, flagRatioW: 2, flagRatioH: 1, tags: ["sun","animal"] },
  { id: 'country:ke', category: 'country', code: 'ke', name: "Kenya", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 580367, flagRatioW: 3, flagRatioH: 2, tags: ["weapon"] },
  { id: 'country:ki', category: 'country', code: 'ki', name: "Kiribati", continent: 'Oceania', colorCount: 6, layout: 'diagonal', areaKm2: 811, flagRatioW: 2, flagRatioH: 1, tags: ["sun","animal"] },
  { id: 'country:kw', category: 'country', code: 'kw', name: "Kuwait", continent: 'Asia', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 17818, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:kg', category: 'country', code: 'kg', name: "Kyrgyzstan", continent: 'Asia', colorCount: 2, layout: 'other', areaKm2: 199951, flagRatioW: 5, flagRatioH: 3, tags: ["sun"] },
  { id: 'country:la', category: 'country', code: 'la', name: "Laos", continent: 'Asia', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 236800, flagRatioW: 3, flagRatioH: 2, aliases: ["Lao PDR"] },
  { id: 'country:lv', category: 'country', code: 'lv', name: "Latvia", continent: 'Europe', colorCount: 2, layout: 'horizontal-stripes', areaKm2: 64559, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:lb', category: 'country', code: 'lb', name: "Lebanon", continent: 'Asia', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 10452, flagRatioW: 3, flagRatioH: 2, tags: ["plant"] },
  { id: 'country:ls', category: 'country', code: 'ls', name: "Lesotho", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 30355, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:lr', category: 'country', code: 'lr', name: "Liberia", continent: 'Africa', colorCount: 3, layout: 'canton', areaKm2: 111369, flagRatioW: 19, flagRatioH: 10, tags: ["star"] },
  { id: 'country:ly', category: 'country', code: 'ly', name: "Libya", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 1759540, flagRatioW: 2, flagRatioH: 1, tags: ["crescent","star"] },
  { id: 'country:li', category: 'country', code: 'li', name: "Liechtenstein", continent: 'Europe', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 160, flagRatioW: 5, flagRatioH: 3 },
  { id: 'country:lt', category: 'country', code: 'lt', name: "Lithuania", continent: 'Europe', colorCount: 1, layout: 'other', areaKm2: 65300, flagRatioW: 5, flagRatioH: 3 },
  { id: 'country:lu', category: 'country', code: 'lu', name: "Luxembourg", continent: 'Europe', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 2586, flagRatioW: 5, flagRatioH: 3 },
  { id: 'country:mg', category: 'country', code: 'mg', name: "Madagascar", continent: 'Africa', colorCount: 3, layout: 'other', areaKm2: 587041, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:mw', category: 'country', code: 'mw', name: "Malawi", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 118484, flagRatioW: 3, flagRatioH: 2, tags: ["sun"] },
  { id: 'country:my', category: 'country', code: 'my', name: "Malaysia", continent: 'Asia', colorCount: 4, layout: 'canton', areaKm2: 330803, flagRatioW: 2, flagRatioH: 1, tags: ["crescent","star"] },
  { id: 'country:mv', category: 'country', code: 'mv', name: "Maldives", continent: 'Asia', colorCount: 3, layout: 'other', areaKm2: 300, flagRatioW: 3, flagRatioH: 2, tags: ["crescent"] },
  { id: 'country:ml', category: 'country', code: 'ml', name: "Mali", continent: 'Africa', colorCount: 3, layout: 'vertical-stripes', areaKm2: 1240192, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:mt', category: 'country', code: 'mt', name: "Malta", continent: 'Europe', colorCount: 2, layout: 'other', areaKm2: 316, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:mh', category: 'country', code: 'mh', name: "Marshall Islands", continent: 'Oceania', colorCount: 3, layout: 'canton', areaKm2: 181, flagRatioW: 19, flagRatioH: 10, tags: ["star"] },
  { id: 'country:mr', category: 'country', code: 'mr', name: "Mauritania", continent: 'Africa', colorCount: 3, layout: 'other', areaKm2: 1030700, flagRatioW: 3, flagRatioH: 2, tags: ["crescent","star"] },
  { id: 'country:mu', category: 'country', code: 'mu', name: "Mauritius", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 2040, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:mx', category: 'country', code: 'mx', name: "Mexico", continent: 'North America', colorCount: 13, layout: 'vertical-stripes', areaKm2: 1964375, flagRatioW: 7, flagRatioH: 4, tags: ["emblem","animal"] },
  { id: 'country:fm', category: 'country', code: 'fm', name: "Micronesia", continent: 'Oceania', colorCount: 2, layout: 'other', areaKm2: 702, flagRatioW: 19, flagRatioH: 10, tags: ["star"], aliases: ["Federated States of Micronesia","FSM"] },
  { id: 'country:md', category: 'country', code: 'md', name: "Moldova", continent: 'Europe', colorCount: 12, layout: 'vertical-stripes', areaKm2: 33846, flagRatioW: 2, flagRatioH: 1, tags: ["emblem"], aliases: ["Republic of Moldova"] },
  { id: 'country:mc', category: 'country', code: 'mc', name: "Monaco", continent: 'Europe', colorCount: 2, layout: 'horizontal-stripes', areaKm2: 2, flagRatioW: 5, flagRatioH: 4 },
  { id: 'country:mn', category: 'country', code: 'mn', name: "Mongolia", continent: 'Asia', colorCount: 2, layout: 'vertical-stripes', areaKm2: 1564110, flagRatioW: 2, flagRatioH: 1, tags: ["emblem","sun"] },
  { id: 'country:me', category: 'country', code: 'me', name: "Montenegro", continent: 'Europe', colorCount: 6, layout: 'other', areaKm2: 13812, flagRatioW: 2, flagRatioH: 1, tags: ["emblem","animal"] },
  { id: 'country:ma', category: 'country', code: 'ma', name: "Morocco", continent: 'Africa', colorCount: 2, layout: 'other', areaKm2: 446550, flagRatioW: 3, flagRatioH: 2, tags: ["emblem","star"] },
  { id: 'country:mz', category: 'country', code: 'mz', name: "Mozambique", continent: 'Africa', colorCount: 6, layout: 'horizontal-stripes', areaKm2: 801590, flagRatioW: 3, flagRatioH: 2, tags: ["star","weapon"] },
  { id: 'country:mm', category: 'country', code: 'mm', name: "Myanmar", continent: 'Asia', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 676578, flagRatioW: 3, flagRatioH: 2, tags: ["star"], aliases: ["Burma"] },
  { id: 'country:na', category: 'country', code: 'na', name: "Namibia", continent: 'Africa', colorCount: 5, layout: 'diagonal', areaKm2: 825615, flagRatioW: 3, flagRatioH: 2, tags: ["sun"] },
  { id: 'country:nr', category: 'country', code: 'nr', name: "Nauru", continent: 'Oceania', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 21, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:np', category: 'country', code: 'np', name: "Nepal", continent: 'Asia', colorCount: 3, layout: 'other', areaKm2: 147181, flagRatioW: 4, flagRatioH: 3, nonRectangularFlag: true, tags: ["sun"] },
  { id: 'country:nl', category: 'country', code: 'nl', name: "Netherlands", continent: 'Europe', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 41850, flagRatioW: 3, flagRatioH: 2, aliases: ["Holland"] },
  { id: 'country:nz', category: 'country', code: 'nz', name: "New Zealand", continent: 'Oceania', colorCount: 4, layout: 'canton', areaKm2: 270467, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:ni', category: 'country', code: 'ni', name: "Nicaragua", continent: 'North America', colorCount: 12, layout: 'horizontal-stripes', areaKm2: 130373, flagRatioW: 5, flagRatioH: 3, tags: ["emblem"] },
  { id: 'country:ne', category: 'country', code: 'ne', name: "Niger", continent: 'Africa', colorCount: 3, layout: 'central-emblem', areaKm2: 1267000, flagRatioW: 7, flagRatioH: 6 },
  { id: 'country:ng', category: 'country', code: 'ng', name: "Nigeria", continent: 'Africa', colorCount: 2, layout: 'vertical-stripes', areaKm2: 923768, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:kp', category: 'country', code: 'kp', name: "North Korea", continent: 'Asia', colorCount: 5, layout: 'horizontal-stripes', areaKm2: 120538, flagRatioW: 2, flagRatioH: 1, tags: ["star"], aliases: ["DPRK","Democratic People's Republic of Korea"] },
  { id: 'country:mk', category: 'country', code: 'mk', name: "North Macedonia", continent: 'Europe', colorCount: 2, layout: 'horizontal-stripes', areaKm2: 25713, flagRatioW: 2, flagRatioH: 1, tags: ["sun"], aliases: ["Macedonia"] },
  { id: 'country:no', category: 'country', code: 'no', name: "Norway", continent: 'Europe', colorCount: 3, layout: 'cross', areaKm2: 323802, flagRatioW: 11, flagRatioH: 8 },
  { id: 'country:om', category: 'country', code: 'om', name: "Oman", continent: 'Asia', colorCount: 3, layout: 'vertical-stripes', areaKm2: 309500, flagRatioW: 7, flagRatioH: 4, tags: ["emblem","weapon"] },
  { id: 'country:pk', category: 'country', code: 'pk', name: "Pakistan", continent: 'Asia', colorCount: 2, layout: 'vertical-stripes', areaKm2: 881912, flagRatioW: 3, flagRatioH: 2, tags: ["crescent","star"] },
  { id: 'country:pw', category: 'country', code: 'pw', name: "Palau", continent: 'Oceania', colorCount: 2, layout: 'central-emblem', areaKm2: 459, flagRatioW: 8, flagRatioH: 5 },
  { id: 'country:pa', category: 'country', code: 'pa', name: "Panama", continent: 'North America', colorCount: 4, layout: 'other', areaKm2: 75417, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:pg', category: 'country', code: 'pg', name: "Papua New Guinea", continent: 'Oceania', colorCount: 4, layout: 'diagonal', areaKm2: 462840, flagRatioW: 4, flagRatioH: 3, tags: ["star","animal"], aliases: ["PNG"] },
  { id: 'country:py', category: 'country', code: 'py', name: "Paraguay", continent: 'South America', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 406752, flagRatioW: 20, flagRatioH: 11, tags: ["emblem"] },
  { id: 'country:pe', category: 'country', code: 'pe', name: "Peru", continent: 'South America', colorCount: 2, layout: 'vertical-stripes', areaKm2: 1285216, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:ph', category: 'country', code: 'ph', name: "Philippines", continent: 'Asia', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 342353, flagRatioW: 2, flagRatioH: 1, tags: ["star","sun"] },
  { id: 'country:pl', category: 'country', code: 'pl', name: "Poland", continent: 'Europe', colorCount: 2, layout: 'horizontal-stripes', areaKm2: 312679, flagRatioW: 8, flagRatioH: 5 },
  { id: 'country:pt', category: 'country', code: 'pt', name: "Portugal", continent: 'Europe', colorCount: 5, layout: 'vertical-stripes', areaKm2: 92090, flagRatioW: 3, flagRatioH: 2, tags: ["emblem"] },
  { id: 'country:qa', category: 'country', code: 'qa', name: "Qatar", continent: 'Asia', colorCount: 2, layout: 'vertical-stripes', areaKm2: 11586, flagRatioW: 28, flagRatioH: 11 },
  { id: 'country:ro', category: 'country', code: 'ro', name: "Romania", continent: 'Europe', colorCount: 3, layout: 'vertical-stripes', areaKm2: 238391, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:ru', category: 'country', code: 'ru', name: "Russia", continent: 'Europe', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 17098242, flagRatioW: 3, flagRatioH: 2, aliases: ["Russian Federation"] },
  { id: 'country:rw', category: 'country', code: 'rw', name: "Rwanda", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 26338, flagRatioW: 3, flagRatioH: 2, tags: ["sun"] },
  { id: 'country:kn', category: 'country', code: 'kn', name: "Saint Kitts and Nevis", continent: 'North America', colorCount: 5, layout: 'other', areaKm2: 261, flagRatioW: 3, flagRatioH: 2, tags: ["star"], aliases: ["St Kitts and Nevis","St. Kitts and Nevis","St Kitts"] },
  { id: 'country:lc', category: 'country', code: 'lc', name: "Saint Lucia", continent: 'North America', colorCount: 4, layout: 'other', areaKm2: 616, flagRatioW: 2, flagRatioH: 1, aliases: ["St Lucia","St. Lucia"] },
  { id: 'country:vc', category: 'country', code: 'vc', name: "Saint Vincent and the Grenadines", continent: 'North America', colorCount: 3, layout: 'vertical-stripes', areaKm2: 389, flagRatioW: 3, flagRatioH: 2, aliases: ["St Vincent and the Grenadines","St Vincent","St. Vincent"] },
  { id: 'country:ws', category: 'country', code: 'ws', name: "Samoa", continent: 'Oceania', colorCount: 3, layout: 'canton', areaKm2: 2842, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:sm', category: 'country', code: 'sm', name: "San Marino", continent: 'Europe', colorCount: 15, layout: 'horizontal-stripes', areaKm2: 61, flagRatioW: 4, flagRatioH: 3, tags: ["emblem","plant","text"] },
  { id: 'country:st', category: 'country', code: 'st', name: "Sao Tome and Principe", continent: 'Africa', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 964, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:sa', category: 'country', code: 'sa', name: "Saudi Arabia", continent: 'Asia', colorCount: 2, layout: 'other', areaKm2: 2149690, flagRatioW: 3, flagRatioH: 2, tags: ["text"] },
  { id: 'country:sn', category: 'country', code: 'sn', name: "Senegal", continent: 'Africa', colorCount: 3, layout: 'vertical-stripes', areaKm2: 196722, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:rs', category: 'country', code: 'rs', name: "Serbia", continent: 'Europe', colorCount: 5, layout: 'other', areaKm2: 88361, flagRatioW: 5, flagRatioH: 3 },
  { id: 'country:sc', category: 'country', code: 'sc', name: "Seychelles", continent: 'Africa', colorCount: 5, layout: 'diagonal', areaKm2: 452, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:sl', category: 'country', code: 'sl', name: "Sierra Leone", continent: 'Africa', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 71740, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:sg', category: 'country', code: 'sg', name: "Singapore", continent: 'Asia', colorCount: 2, layout: 'horizontal-stripes', areaKm2: 710, flagRatioW: 3, flagRatioH: 2, tags: ["crescent","star"] },
  { id: 'country:sk', category: 'country', code: 'sk', name: "Slovakia", continent: 'Europe', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 49037, flagRatioW: 3, flagRatioH: 2, tags: ["emblem"] },
  { id: 'country:si', category: 'country', code: 'si', name: "Slovenia", continent: 'Europe', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 20273, flagRatioW: 2, flagRatioH: 1, tags: ["emblem","star"] },
  { id: 'country:sb', category: 'country', code: 'sb', name: "Solomon Islands", continent: 'Oceania', colorCount: 4, layout: 'other', areaKm2: 28896, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:so', category: 'country', code: 'so', name: "Somalia", continent: 'Africa', colorCount: 2, layout: 'other', areaKm2: 637657, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:za', category: 'country', code: 'za', name: "South Africa", continent: 'Africa', colorCount: 6, layout: 'other', areaKm2: 1221037, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:kr', category: 'country', code: 'kr', name: "South Korea", continent: 'Asia', colorCount: 4, layout: 'central-emblem', areaKm2: 100210, flagRatioW: 3, flagRatioH: 2, aliases: ["Korea","Republic of Korea"] },
  { id: 'country:ss', category: 'country', code: 'ss', name: "South Sudan", continent: 'Africa', colorCount: 6, layout: 'horizontal-stripes', areaKm2: 619745, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:es', category: 'country', code: 'es', name: "Spain", continent: 'Europe', colorCount: 6, layout: 'horizontal-stripes', areaKm2: 505992, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:lk', category: 'country', code: 'lk', name: "Sri Lanka", continent: 'Asia', colorCount: 4, layout: 'other', areaKm2: 65610, flagRatioW: 2, flagRatioH: 1, tags: ["animal","plant","weapon"] },
  { id: 'country:sd', category: 'country', code: 'sd', name: "Sudan", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 1886068, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:sr', category: 'country', code: 'sr', name: "Suriname", continent: 'South America', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 163820, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:se', category: 'country', code: 'se', name: "Sweden", continent: 'Europe', colorCount: 2, layout: 'cross', areaKm2: 450295, flagRatioW: 8, flagRatioH: 5 },
  { id: 'country:ch', category: 'country', code: 'ch', name: "Switzerland", continent: 'Europe', colorCount: 2, layout: 'cross', areaKm2: 41284, flagRatioW: 1, flagRatioH: 1 },
  { id: 'country:sy', category: 'country', code: 'sy', name: "Syria", continent: 'Asia', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 185180, flagRatioW: 3, flagRatioH: 2, tags: ["star"], aliases: ["Syrian Arab Republic"] },
  { id: 'country:tw', category: 'country', code: 'tw', name: "Taiwan", continent: 'Asia', colorCount: 3, layout: 'other', areaKm2: 36193, flagRatioW: 3, flagRatioH: 2, tags: ["sun"] },
  { id: 'country:tj', category: 'country', code: 'tj', name: "Tajikistan", continent: 'Asia', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 143100, flagRatioW: 2, flagRatioH: 1, tags: ["star"] },
  { id: 'country:tz', category: 'country', code: 'tz', name: "Tanzania", continent: 'Africa', colorCount: 4, layout: 'diagonal', areaKm2: 945087, flagRatioW: 3, flagRatioH: 2, aliases: ["United Republic of Tanzania"] },
  { id: 'country:th', category: 'country', code: 'th', name: "Thailand", continent: 'Asia', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 513120, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:tl', category: 'country', code: 'tl', name: "Timor-Leste", continent: 'Asia', colorCount: 4, layout: 'diagonal', areaKm2: 14874, flagRatioW: 2, flagRatioH: 1, tags: ["star"], aliases: ["East Timor"] },
  { id: 'country:tg', category: 'country', code: 'tg', name: "Togo", continent: 'Africa', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 56785, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:to', category: 'country', code: 'to', name: "Tonga", continent: 'Oceania', colorCount: 2, layout: 'other', areaKm2: 747, flagRatioW: 2, flagRatioH: 1 },
  { id: 'country:tt', category: 'country', code: 'tt', name: "Trinidad and Tobago", continent: 'North America', colorCount: 3, layout: 'diagonal', areaKm2: 5130, flagRatioW: 5, flagRatioH: 3, aliases: ["Trinidad"] },
  { id: 'country:tn', category: 'country', code: 'tn', name: "Tunisia", continent: 'Africa', colorCount: 2, layout: 'central-emblem', areaKm2: 163610, flagRatioW: 3, flagRatioH: 2, tags: ["crescent","star"] },
  { id: 'country:tr', category: 'country', code: 'tr', name: "Turkey", continent: 'Asia', colorCount: 2, layout: 'central-emblem', areaKm2: 783562, flagRatioW: 3, flagRatioH: 2, tags: ["crescent","star"], aliases: ["Turkiye","Türkiye"] },
  { id: 'country:tm', category: 'country', code: 'tm', name: "Turkmenistan", continent: 'Asia', colorCount: 5, layout: 'vertical-stripes', areaKm2: 488100, flagRatioW: 3, flagRatioH: 2, tags: ["crescent","star","plant"] },
  { id: 'country:tv', category: 'country', code: 'tv', name: "Tuvalu", continent: 'Oceania', colorCount: 5, layout: 'canton', areaKm2: 26, flagRatioW: 2, flagRatioH: 1, tags: ["star","map-silhouette"] },
  { id: 'country:ug', category: 'country', code: 'ug', name: "Uganda", continent: 'Africa', colorCount: 7, layout: 'horizontal-stripes', areaKm2: 241550, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:ua', category: 'country', code: 'ua', name: "Ukraine", continent: 'Europe', colorCount: 2, layout: 'horizontal-stripes', areaKm2: 603500, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:ae', category: 'country', code: 'ae', name: "United Arab Emirates", continent: 'Asia', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 83600, flagRatioW: 2, flagRatioH: 1, aliases: ["UAE"] },
  { id: 'country:gb', category: 'country', code: 'gb', name: "United Kingdom", continent: 'Europe', colorCount: 3, layout: 'other', areaKm2: 242900, flagRatioW: 2, flagRatioH: 1, aliases: ["UK","Great Britain"] },
  { id: 'country:us', category: 'country', code: 'us', name: "United States", continent: 'North America', colorCount: 3, layout: 'canton', areaKm2: 9372610, flagRatioW: 19, flagRatioH: 10, tags: ["star"], aliases: ["USA","US","United States of America"] },
  { id: 'country:uy', category: 'country', code: 'uy', name: "Uruguay", continent: 'South America', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 181034, flagRatioW: 3, flagRatioH: 2, tags: ["sun"] },
  { id: 'country:uz', category: 'country', code: 'uz', name: "Uzbekistan", continent: 'Asia', colorCount: 4, layout: 'horizontal-stripes', areaKm2: 447400, flagRatioW: 2, flagRatioH: 1, tags: ["crescent","star"] },
  { id: 'country:vu', category: 'country', code: 'vu', name: "Vanuatu", continent: 'Oceania', colorCount: 4, layout: 'other', areaKm2: 12189, flagRatioW: 3, flagRatioH: 2, tags: ["animal","plant"] },
  { id: 'country:va', category: 'country', code: 'va', name: "Vatican City", continent: 'Europe', colorCount: 5, layout: 'other', areaKm2: 0, flagRatioW: 1, flagRatioH: 1, tags: ["emblem"], aliases: ["Holy See"] },
  { id: 'country:ve', category: 'country', code: 've', name: "Venezuela", continent: 'South America', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 916445, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:vn', category: 'country', code: 'vn', name: "Vietnam", continent: 'Asia', colorCount: 2, layout: 'other', areaKm2: 331212, flagRatioW: 3, flagRatioH: 2, tags: ["star"] },
  { id: 'country:ye', category: 'country', code: 'ye', name: "Yemen", continent: 'Asia', colorCount: 3, layout: 'horizontal-stripes', areaKm2: 527968, flagRatioW: 3, flagRatioH: 2 },
  { id: 'country:zm', category: 'country', code: 'zm', name: "Zambia", continent: 'Africa', colorCount: 4, layout: 'other', areaKm2: 752612, flagRatioW: 3, flagRatioH: 2, tags: ["animal"] },
  { id: 'country:zw', category: 'country', code: 'zw', name: "Zimbabwe", continent: 'Africa', colorCount: 7, layout: 'horizontal-stripes', areaKm2: 390757, flagRatioW: 2, flagRatioH: 1, tags: ["star","animal"] },
]
